const apiKey = "f7b444cfa99e4757bdb205128242011";

export const weatherImages = {
  "partly cloudy": require("../assets/images/partlycloudy.png"),
  "moderate rain": require("../assets/images/moderaterain.png"),
  "patchy rain possible": require("../assets/images/moderaterain.png"),
  "patchy rain nearby": require("../assets/images/nearrain.png"),
  "patchy light snow": require("../assets/images/lightsnow.png"),
  "light snow": require("../assets/images/lightsnow.png"),
  "light drizzle": require("../assets/images/lightdrizzle.png"),
  "light rain shower": require("../assets/images/lightrain.png"),
  mist: require("../assets/images/mist.png"),
  sunny: require("../assets/images/sun.png"),
  clear: require("../assets/images/sun.png"),
  overcast: require("../assets/images/cloud.png"),
  cloudy: require("../assets/images/cloud.png"),
  "light rain": require("../assets/images/lightrain.png"),
  "moderate rain at times": require("../assets/images/moderaterain.png"),
  "heavy rain": require("../assets/images/heavyrain.png"),
  "heavy rain at times": require("../assets/images/heavyrain.png"),
  "moderate or heavy freezing rain": require("../assets/images/heavyrain.png"),
  "moderate or heavy rain shower": require("../assets/images/heavyrain.png"),
  "moderate or heavy rain with thunder": require("../assets/images/heavyrain.png"),
  other: require("../assets/images/moderaterain.png"),
};
